"""empty message

Revision ID: 11daece8174b
Revises: 575f5d88e6fc
Create Date: 2020-05-06 18:35:47.948592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11daece8174b'
down_revision = '575f5d88e6fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'shows', 'venues', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_column('shows', 'venue_id')
    # ### end Alembic commands ###
