"""empty message

Revision ID: 23251d5fb1e7
Revises: a956e520c79e
Create Date: 2020-06-20 23:24:36.741592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23251d5fb1e7'
down_revision = 'a956e520c79e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('website', sa.String(length=120), nullable=True))
    op.drop_column('venues', 'webiste')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('webiste', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('venues', 'website')
    # ### end Alembic commands ###
